// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using generateqrcode.Data;

#nullable disable

namespace GenerateQrCode.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250914094404_InitialDatabase")]
    partial class InitialDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("generateqrcode.Data.Models.DonViHanhChinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cap")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaPX")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaQH")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaTP")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhuongXaThiTran")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QuanHuyen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenTiengAnh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TinhThanhPho")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DonViHanhChinhs");
                });
#pragma warning restore 612, 618
        }
    }
}
